In [39]:
import pandas as pd
import numpy as np

In [40]:
dados_semestre_1="Preços semestrais - AUTOMOTIVOS_2025.01.csv"

df_semestre_1=pd.read_csv(dados_semestre_1, sep = ";" , encoding ='latin1')

df_semestre_1

C:\Users\wallace.farias\AppData\Local\Temp\ipykernel_15208\4276783858.py:3: DtypeWarning: Columns (0: ï»¿Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Valor de Venda, 13: Unidade de Medida, 14: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_semestre_1=pd.read_csv(dados_semestre_1, sep = ";" , encoding ='latin1')

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN
3,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,ETANOL,01/01/2025,"5,19",NaN,R$ / litro,RAIZEN
4,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,GASOLINA,01/01/2025,"6,53",NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
dados_semestre_2="Preços semestrais - AUTOMOTIVOS_2025.02.csv"

df_semestre_2=pd.read_csv(dados_semestre_2, sep = ";" , encoding ='latin1')

df_semestre_2

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,4431113000100,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,DIESEL,01/07/2025,"6,69",NaN,R$ / litro,BRANCA
1,N,AP,MACAPA,SEPE TIARAJU EMPREENDIMENTOS LTDA,5297501000286,RUA SETENTRIONAL,S/N,ESQUINA COM BEIRA RIO,ARAXÃ,68903-640,DIESEL,01/07/2025,"6,33",NaN,R$ / litro,BRANCA
2,NE,BA,IPIRA,AUTO POSTO AUGUSTU'S LTDA,2448248000145,SITIO SAO JOSE,SN,NaN,SEDE,44600-000,DIESEL,01/07/2025,"6,9",NaN,R$ / litro,ALE
3,NE,BA,ITAMARAJU,CODEPEL -COMERCIO DE DERIVADOS DE PETROLEO LTDA,5696709000197,AVENIDA PERIMENRAL,348,TERREO,CENTRO,45836-000,DIESEL,01/07/2025,"5,99",NaN,R$ / litro,BRANCA
4,NE,BA,ITAMARAJU,BENTIVI DERIVADOS DE PETROLEO LTDA,13683818000106,RODOVIA BR 101,S/N,KM 808,SEDE,45836-000,DIESEL,01/07/2025,"5,92",NaN,R$ / litro,IPIRANGA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384203,NE,BA,ALAGOINHAS,2 A COMERCIO DE COMBUSTIVEIS GNV E LUBRIFICANT...,14238511000150,RODOVIA BR 101 KM 116,S/N,SALA 01,CENTRO,48005-440,GNV,31/12/2025,"4,38",NaN,R$ / m3,LARCO
384204,NE,PB,BAYEUX,PETROGAS COMERCIO DE COMBUSTIVEIS LTDA,21553439000111,AVENIDA LIBERDADE,3545,ANDAR: 1; ANEXO: A;,SESI,58306-000,GNV,31/12/2025,"4,85",NaN,R$ / m3,ALE
384205,NE,BA,ILHEUS,BATISTA COMERCIO DE COMBUSTIVEIS E LUBRIFICANT...,28562491000183,AVENIDA FERROVIARIA,S/N,KM 05 RODOVIA ILHEUS,IGUAPE,45658-340,GNV,31/12/2025,"4,73",NaN,R$ / m3,BRANCA
384206,SE,SP,JACAREI,AUTO POSTO BRANCO DE CASTELO LTDA,68912864000385,AVENIDA SIQUEIRA CAMPOS,641,NaN,CENTRO,12308-190,GNV,31/12/2025,"3,99",NaN,R$ / m3,VIBRA
384207,S,RS,LAJEADO,SIM REDE DE POSTOS LTDA,7473735018714,RODOVIA ERS-130,2285,KM 72.8,SANTO ANDRE,95912-000,GNV,31/12/2025,"5,65",NaN,R$ / m3,CHARRUA

In [42]:
df_semestre_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 429523 entries, 0 to 429522
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ï»¿Regiao - Sigla  420409 non-null  str
 1   Estado - Sigla     420409 non-null  str
 2   Municipio          420409 non-null  str
 3   Revenda            420409 non-null  str
 4   CNPJ da Revenda    420409 non-null  str
 5   Nome da Rua        420409 non-null  str
 6   Numero Rua         420351 non-null  str
 7   Complemento        96615 non-null   str
 8   Bairro             419547 non-null  str
 9   Cep                420409 non-null  str
 10  Produto            420409 non-null  str
 11  Data da Coleta     420409 non-null  str
 12  Valor de Venda     420409 non-null  str
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  420409 non-null  str
 15  Bandeira           420409 non-null  str
dtypes: float64(1), str(15)
memory usage: 52.4 MB

In [43]:
df_semestre_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 384208 entries, 0 to 384207
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ï»¿Regiao - Sigla  384208 non-null  str
 1   Estado - Sigla     384208 non-null  str
 2   Municipio          384208 non-null  str
 3   Revenda            384208 non-null  str
 4   CNPJ da Revenda    384208 non-null  int64
 5   Nome da Rua        384208 non-null  str
 6   Numero Rua         384184 non-null  str
 7   Complemento        86707 non-null   str
 8   Bairro             383546 non-null  str
 9   Cep                384208 non-null  str
 10  Produto            384208 non-null  str
 11  Data da Coleta     384208 non-null  str
 12  Valor de Venda     384208 non-null  str
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  384208 non-null  str
 15  Bandeira           384208 non-null  str
dtypes: float64(1), int64(1), str(14)
memory usage: 46.9 MB

In [44]:
df_semestre_2['CNPJ da Revenda'] = df_semestre_2['CNPJ da Revenda'].astype(str)

In [45]:
df_anp=pd.concat([df_semestre_1,df_semestre_2], ignore_index = True)
df_anp

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN
3,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,ETANOL,01/01/2025,"5,19",NaN,R$ / litro,RAIZEN
4,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,GASOLINA,01/01/2025,"6,53",NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813726,NE,BA,ALAGOINHAS,2 A COMERCIO DE COMBUSTIVEIS GNV E LUBRIFICANT...,14238511000150,RODOVIA BR 101 KM 116,S/N,SALA 01,CENTRO,48005-440,GNV,31/12/2025,"4,38",NaN,R$ / m3,LARCO
813727,NE,PB,BAYEUX,PETROGAS COMERCIO DE COMBUSTIVEIS LTDA,21553439000111,AVENIDA LIBERDADE,3545,ANDAR: 1; ANEXO: A;,SESI,58306-000,GNV,31/12/2025,"4,85",NaN,R$ / m3,ALE
813728,NE,BA,ILHEUS,BATISTA COMERCIO DE COMBUSTIVEIS E LUBRIFICANT...,28562491000183,AVENIDA FERROVIARIA,S/N,KM 05 RODOVIA ILHEUS,IGUAPE,45658-340,GNV,31/12/2025,"4,73",NaN,R$ / m3,BRANCA
813729,SE,SP,JACAREI,AUTO POSTO BRANCO DE CASTELO LTDA,68912864000385,AVENIDA SIQUEIRA CAMPOS,641,NaN,CENTRO,12308-190,GNV,31/12/2025,"3,99",NaN,R$ / m3,VIBRA
813730,S,RS,LAJEADO,SIM REDE DE POSTOS LTDA,7473735018714,RODOVIA ERS-130,2285,KM 72.8,SANTO ANDRE,95912-000,GNV,31/12/2025,"5,65",NaN,R$ / m3,CHARRUA

In [46]:
df_anp['Valor de Venda']= df_anp['Valor de Venda'].str.replace(',','.').astype(float)
df_anp

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,6.29,NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,6.49,NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,6.19,NaN,R$ / litro,RAIZEN
3,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,ETANOL,01/01/2025,5.19,NaN,R$ / litro,RAIZEN
4,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,GASOLINA,01/01/2025,6.53,NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813726,NE,BA,ALAGOINHAS,2 A COMERCIO DE COMBUSTIVEIS GNV E LUBRIFICANT...,14238511000150,RODOVIA BR 101 KM 116,S/N,SALA 01,CENTRO,48005-440,GNV,31/12/2025,4.38,NaN,R$ / m3,LARCO
813727,NE,PB,BAYEUX,PETROGAS COMERCIO DE COMBUSTIVEIS LTDA,21553439000111,AVENIDA LIBERDADE,3545,ANDAR: 1; ANEXO: A;,SESI,58306-000,GNV,31/12/2025,4.85,NaN,R$ / m3,ALE
813728,NE,BA,ILHEUS,BATISTA COMERCIO DE COMBUSTIVEIS E LUBRIFICANT...,28562491000183,AVENIDA FERROVIARIA,S/N,KM 05 RODOVIA ILHEUS,IGUAPE,45658-340,GNV,31/12/2025,4.73,NaN,R$ / m3,BRANCA
813729,SE,SP,JACAREI,AUTO POSTO BRANCO DE CASTELO LTDA,68912864000385,AVENIDA SIQUEIRA CAMPOS,641,NaN,CENTRO,12308-190,GNV,31/12/2025,3.99,NaN,R$ / m3,VIBRA
813730,S,RS,LAJEADO,SIM REDE DE POSTOS LTDA,7473735018714,RODOVIA ERS-130,2285,KM 72.8,SANTO ANDRE,95912-000,GNV,31/12/2025,5.65,NaN,R$ / m3,CHARRUA

In [47]:
df_anp.info()

<class 'pandas.DataFrame'>
RangeIndex: 813731 entries, 0 to 813730
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ï»¿Regiao - Sigla  804617 non-null  str
 1   Estado - Sigla     804617 non-null  str
 2   Municipio          804617 non-null  str
 3   Revenda            804617 non-null  str
 4   CNPJ da Revenda    804617 non-null  str
 5   Nome da Rua        804617 non-null  str
 6   Numero Rua         804535 non-null  str
 7   Complemento        183322 non-null  str
 8   Bairro             803093 non-null  str
 9   Cep                804617 non-null  str
 10  Produto            804617 non-null  str
 11  Data da Coleta     804617 non-null  str
 12  Valor de Venda     804617 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  804617 non-null  str
 15  Bandeira           804617 non-null  str
dtypes: float64(2), str(14)
memory usage: 99.3 MB

In [48]:
df_gasolina=df_anp.loc[df_anp['Produto']=='GASOLINA']
df_etanol=df_anp.loc[df_anp['Produto']=='ETANOL']

In [49]:
df_gasolina

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,6.29,NaN,R$ / litro,RAIZEN
4,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,GASOLINA,01/01/2025,6.53,NaN,R$ / litro,RAIZEN
8,NE,CE,SOBRAL,CENTER POSTO COMERCIAL LTDA,02.905.892/0001-03,AVENIDA JOSE ARIMATEIA MONTE E SILVA,425,NaN,CAMPOS DOS VELHOS,62114-000,GASOLINA,01/01/2025,6.69,NaN,R$ / litro,VIBRA
12,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0001-54,AVENIDA MONSENHOR JOSE ALOISIO PINTO,80,LOJA 01,DOM EXPEDITO,62050-255,GASOLINA,01/01/2025,6.69,NaN,R$ / litro,IPIRANGA
16,NE,CE,SOBRAL,POSTO SAO DOMINGOS LTDA,69.366.128/0001-70,AVENIDA DOUTOR GUARANI,854,NaN,JOCELY DANTAS DE ANDRADE TORRES,62042-030,GASOLINA,01/01/2025,6.69,NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724883,SE,MG,JANAUBA,M F B NOGUEIRA POSTO DE COMBUSTIVEL LTDA,32275352000227,AVENIDA MILITAO JOSE DOS SANTOS,2596,NaN,PLANALTO,39445-583,GASOLINA,31/12/2025,6.29,NaN,R$ / litro,IPIRANGA
724884,S,PR,PONTA GROSSA,AUTO POSTO PROGRESSO PONTA GROSSA LTDA,47536308000110,AVENIDA VISCONDE DE TAUNAY,460,NaN,CENTRO,84051-000,GASOLINA,31/12/2025,6.49,NaN,R$ / litro,BRANCA
724885,SE,MG,ARAGUARI,COMBUSTIVEIS OURO NEGRO IV LTDA,52721170000169,AVENIDA MATO GROSSO,1740,NaN,CENTRO,38440-046,GASOLINA,31/12/2025,5.89,NaN,R$ / litro,IPIRANGA
724886,S,PR,SAO JOSE DOS PINHAIS,POSTO LINHA VERDE LTDA,38824625000736,RUA ESTELA MARI REZENDE,10789,NaN,BORDA DO CAMPO,83075-452,GASOLINA,31/12/2025,6.79,NaN,R$ / litro,IPIRANGA
724887,SE,MG,VICOSA,WMC COMERCIO DE COMBUSTIVEIS LTDA,52268574000149,AVENIDA JACOB LOPES DE CASTRO,920,NaN,NOVA ERA,36574-192,GASOLINA,31/12/2025,6.19,NaN,R$ / litro,BRANCA

In [50]:
df_etanol

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
3,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,ETANOL,01/01/2025,5.19,NaN,R$ / litro,RAIZEN
7,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,ETANOL,01/01/2025,5.29,NaN,R$ / litro,RAIZEN
11,NE,CE,SOBRAL,CENTER POSTO COMERCIAL LTDA,02.905.892/0001-03,AVENIDA JOSE ARIMATEIA MONTE E SILVA,425,NaN,CAMPOS DOS VELHOS,62114-000,ETANOL,01/01/2025,5.29,NaN,R$ / litro,VIBRA
15,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0001-54,AVENIDA MONSENHOR JOSE ALOISIO PINTO,80,LOJA 01,DOM EXPEDITO,62050-255,ETANOL,01/01/2025,5.29,NaN,R$ / litro,IPIRANGA
19,NE,CE,SOBRAL,POSTO SAO DOMINGOS LTDA,69.366.128/0001-70,AVENIDA DOUTOR GUARANI,854,NaN,JOCELY DANTAS DE ANDRADE TORRES,62042-030,ETANOL,01/01/2025,5.29,NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623278,SE,MG,JANAUBA,M F B NOGUEIRA POSTO DE COMBUSTIVEL LTDA,32275352000227,AVENIDA MILITAO JOSE DOS SANTOS,2596,NaN,PLANALTO,39445-583,ETANOL,31/12/2025,4.49,NaN,R$ / litro,IPIRANGA
623279,S,PR,PONTA GROSSA,AUTO POSTO PROGRESSO PONTA GROSSA LTDA,47536308000110,AVENIDA VISCONDE DE TAUNAY,460,NaN,CENTRO,84051-000,ETANOL,31/12/2025,4.49,NaN,R$ / litro,BRANCA
623280,SE,MG,ARAGUARI,COMBUSTIVEIS OURO NEGRO IV LTDA,52721170000169,AVENIDA MATO GROSSO,1740,NaN,CENTRO,38440-046,ETANOL,31/12/2025,4.39,NaN,R$ / litro,IPIRANGA
623281,S,PR,SAO JOSE DOS PINHAIS,POSTO LINHA VERDE LTDA,38824625000736,RUA ESTELA MARI REZENDE,10789,NaN,BORDA DO CAMPO,83075-452,ETANOL,31/12/2025,4.79,NaN,R$ / litro,IPIRANGA
623282,SE,MG,VICOSA,WMC COMERCIO DE COMBUSTIVEIS LTDA,52268574000149,AVENIDA JACOB LOPES DE CASTRO,920,NaN,NOVA ERA,36574-192,ETANOL,31/12/2025,4.59,NaN,R$ / litro,BRANCA

In [52]:
df_media_est_gaso = df_gasolina.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda',ascending=False)

df_media_est_gaso.head()

   Estado - Sigla  Valor de Venda
0              AC        7.671043
2              AM        7.226496
21             RR        6.947907
20             RO        6.914577
24             SE        6.547728

In [54]:
df_media_est_etanol = df_etanol.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda',ascending=False)

df_media_est_etanol.head()

   Estado - Sigla  Valor de Venda
0              AC        5.450321
2              AM        5.429408
3              AP        5.428462
20             RO        5.213401
21             RR        5.164806

In [55]:
# Comparação Regional de Preços
df_media_reg_gaso=df_gasolina.groupby('ï»¿Regiao - Sigla')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda',ascending=False)

df_media_reg_gaso

  ï»¿Regiao - Sigla  Valor de Venda
1                 N        6.716720
3                 S        6.331845
0                CO        6.293839
2                NE        6.288195
4                SE        6.115093

In [ ]:
df_media_reg_etanol = df_etanol.groupby('ï»¿Regiao - Sigla')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda',ascending=False)

df_media_reg_etanol

  ï»¿Regiao - Sigla  Valor de Venda
1                 N        5.085354
2                NE        4.845289
3                 S        4.629784
0                CO        4.352734
4                SE        4.237751

In [59]:
df_dez_maiores_munic_gasol=df_gasolina.groupby('Municipio')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda',ascending=False)

df_dez_maiores_munic_gasol.head(10)

           Municipio  Valor de Venda
276        PARINTINS        8.313433
120  CRUZEIRO DO SUL        7.992080
316       RIO BRANCO        7.492689
46           BARUERI        7.257318
38              BAGE        7.190867
233           MANAUS        7.069509
125  DELMIRO GOUVEIA        7.059354
332         SANTAREM        7.044586
291    PIMENTA BUENO        7.044259
6           ALENQUER        7.032374

In [60]:
df_dez_maiores_munic_etanol=df_etanol.groupby('Municipio')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda',ascending=False)

df_dez_maiores_munic_etanol.head(10)

                 Municipio  Valor de Venda
119        CRUZEIRO DO SUL        5.935372
406                VILHENA        5.675648
328  SANTANA DO LIVRAMENTO        5.617932
183              ITAPIPOCA        5.592132
115                CRATEUS        5.477391
232                 MANAUS        5.445055
102                   CODO        5.441439
228                 MACAPA        5.428462
162                    ICO        5.343868
231             MANACAPURU        5.338944

In [63]:
df_dez_maiores_munic_gasol.tail(10)

               Municipio  Valor de Venda
253              NITEROI        5.855828
26            ARARAQUARA        5.853007
380             TERESINA        5.848389
83          CAMPO GRANDE        5.818789
13            ANANINDEUA        5.779130
195              JACAREI        5.762268
377              TAUBATE        5.749248
148             GOIATUBA        5.737596
353             SAO LUIS        5.709328
348  SAO JOSE DE RIBAMAR        5.677958

In [64]:
df_dez_maiores_munic_etanol.tail(10)

                 Municipio  Valor de Venda
197                  JALES        3.921549
235                MARILIA        3.908255
307    PRESIDENTE PRUDENTE        3.897089
147               GOIATUBA        3.890171
413            VOTUPORANGA        3.889227
82            CAMPO GRANDE        3.860465
55                 BIRIGUI        3.845749
222                   LINS        3.829775
18               ARACATUBA        3.761291
346  SAO JOSE DO RIO PRETO        3.741439